/* Auto-generated by genmsg_cpp for file /home/cody/fuerte_workspace/sandbox/CodyLegoBot/msg/commandsend.msg */
#ifndef CODYLEGOBOT_MESSAGE_COMMANDSEND_H
#define CODYLEGOBOT_MESSAGE_COMMANDSEND_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace CodyLegoBot
{
template <class ContainerAllocator>
struct commandsend_ {
  typedef commandsend_<ContainerAllocator> Type;

  commandsend_()
  : cds()
  {
  }

  commandsend_(const ContainerAllocator& _alloc)
  : cds(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _cds_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  cds;


  typedef boost::shared_ptr< ::CodyLegoBot::commandsend_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::CodyLegoBot::commandsend_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct commandsend
typedef  ::CodyLegoBot::commandsend_<std::allocator<void> > commandsend;

typedef boost::shared_ptr< ::CodyLegoBot::commandsend> commandsendPtr;
typedef boost::shared_ptr< ::CodyLegoBot::commandsend const> commandsendConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::CodyLegoBot::commandsend_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::CodyLegoBot::commandsend_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace CodyLegoBot

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::CodyLegoBot::commandsend_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::CodyLegoBot::commandsend_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::CodyLegoBot::commandsend_<ContainerAllocator> > {
  static const char* value() 
  {
    return "0753234295f3099569ee5ddb4e7f2d72";
  }

  static const char* value(const  ::CodyLegoBot::commandsend_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x0753234295f30995ULL;
  static const uint64_t static_value2 = 0x69ee5ddb4e7f2d72ULL;
};

template<class ContainerAllocator>
struct DataType< ::CodyLegoBot::commandsend_<ContainerAllocator> > {
  static const char* value() 
  {
    return "CodyLegoBot/commandsend";
  }

  static const char* value(const  ::CodyLegoBot::commandsend_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::CodyLegoBot::commandsend_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string cds\n\
\n\
";
  }

  static const char* value(const  ::CodyLegoBot::commandsend_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::CodyLegoBot::commandsend_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.cds);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct commandsend_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::CodyLegoBot::commandsend_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::CodyLegoBot::commandsend_<ContainerAllocator> & v) 
  {
    s << indent << "cds: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.cds);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CODYLEGOBOT_MESSAGE_COMMANDSEND_H

